export const SET_ASSET = "SET_ASSET";
export const SET_ACTIVE_ASSET = "SET_ACTIVE_ASSET";
export const RECEIVE_ASSET = "RECEIVE_ASSET";
export const RECEIVE_SUMMARY_DATA = "RECEIVE_SUMMARY_DATA";
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
export const RECEIVE_USER_RESERVE_DATA = "RECEIVE_USER_RESERVE_DATA";
export const SET_USER_ADDRESS = "SET_USER_ADDRESS"